# fly.toml app configuration file generated for imperium-tattoo on 2024-08-19T09:01:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'imperium-tattoo'
primary_region = 'gru'

[build]

[env]
  APP_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
