app = 'imperium-tattoo'
primary_region = 'gru'

[build]
[build.args]
GO_VERSION = '1.22.5'

[env]
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
