name: Fly Production Deployment
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create fly.toml
        run: echo ${{ secrets.FLY_PRD }} > fly.toml
      - name: Fly deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
